### ISSUE TITLE
Bring in jsonapi-renderer bugfix

### ISSUE THREAD

**Issue by bastianlb** [jsonapi-rb/jsonapi-rb#1]
I'm encountering the following error:
```
#<NoMethodError: undefined method `merge!' for #<Set: {}> Did you mean?  merge>
jsonapi-renderer (0.1.1) lib/jsonapi/renderer/resources_processor.rb:51:in `traverse_resource'
jsonapi-renderer (0.1.1) lib/jsonapi/renderer/resources_processor.rb:43:in `traverse_queue'
jsonapi-renderer (0.1.1) lib/jsonapi/renderer/resources_processor.rb:29:in `traverse_resources'
```

This appears to be fixed here: https://github.com/jsonapi-rb/jsonapi-renderer/commit/8fa349b5d4dd87f027d538ebed475bf67893759b

Can you bring this into the `jsonapi-rb` and `jsonapi-rails` master branches? I'm having trouble installing.

```
Bundler could not find compatible versions for gem "jsonapi-renderer":
  In Gemfile:
    jsonapi-renderer (~> 0.1.2)

    jsonapi-rails was resolved to 0.1.1, which depends on
      jsonapi-rb (= 0.1.1) was resolved to 0.1.1, which depends on
        jsonapi-serializable (= 0.1.1) was resolved to 0.1.1, which depends on
          jsonapi-renderer (= 0.1.1)
```

**Comment by beauby** [comment]
Definitely – sorry about that. Will try to cut a new release today!

**Comment by beauby** [comment]
Just pushed a new version. Could you give it a try? (A simple `bundle update` should do.)

**Comment by bastianlb** [comment]
This works, thanks!
